CREATE DATABASE IF NOT EXISTS CountMoney;
GRANT ALL PRIVILEGES ON CountMoney.* TO 'corentin'@'%';
FLUSH PRIVILEGES;
SELECT SLEEP(1);

CREATE DATABASE IF NOT EXISTS CountMoneyTest;
GRANT ALL PRIVILEGES ON CountMoneyTest.* TO 'corentin'@'%';
FLUSH PRIVILEGES;