version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      # - ./init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    restart: always
    # networks:
    #   - backend
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   restart: always
  #   networks:
  #     - backend
# networks:
#   backend:
#     driver: bridge
