name: Frontend docker image

on:
  push:
    branches:
      - develop

jobs:
  build_and_publish:
    if: github.repository == 'cyrcab/count-money'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push the image backend
        run: |
          docker login --username cyrcab --password ${{ secrets.TOKEN }} ghcr.io
          docker build . -t ghcr.io/cyrcab/monorepo-backend:develop
          docker push ghcr.io/cyrcab/monorepo-backend:develop
